using Dapper;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;

namespace FolioLibrary
{
    public class FolioDapperContext : IDisposable
    {
        private string connectionString;
        public int? CommandTimeout { get; set; } = 90;
        private DbConnection dbConnection;
        private DbTransaction dbTransaction;
        private string providerName;
        public readonly static TraceSource traceSource = new TraceSource("FolioLibrary", SourceLevels.Information);

        public bool IsMySql => providerName == "MySql.Data.MySqlClient";
        public bool IsPostgreSql => providerName == "Npgsql";
        public bool IsSqlServer => providerName == "System.Data.SqlClient";

        public FolioDapperContext() : this("FolioContext") { }

        public FolioDapperContext(string name)
        {
            providerName = ConfigurationManager.ConnectionStrings[name].ProviderName;
            connectionString = ConfigurationManager.ConnectionStrings[name].ConnectionString;
        }

        private DbConnection Connection
        {
            get
            {
                if (dbConnection == null)
                {
                    dbConnection = DbProviderFactories.GetFactory(IsMySql ? "MySql.Data.MySqlClient2" : providerName).CreateConnection();
                    dbConnection.ConnectionString = connectionString;
                    dbConnection.Open();
                    if (IsMySql) dbConnection.Execute("SET SQL_MODE = 'ANSI'");
                }
                return dbConnection;
            }
        }

        private DbTransaction Transaction
        {
            get
            {
                if (dbTransaction == null) dbTransaction = Connection.BeginTransaction(IsolationLevel.ReadCommitted);
                return dbTransaction;
            }
        }

        public Account FindAccount(Guid id) => Query<Account>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}accounts WHERE id = @id", new { id }).SingleOrDefault();
        public Account2 FindAccount2(Guid id) => Query<Account2>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}account WHERE id = @id", new { id }).SingleOrDefault();
        public Address FindAddress(Guid id) => Query<Address>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}address WHERE id = @id", new { id }).SingleOrDefault();
        public AddressType FindAddressType(Guid id) => Query<AddressType>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}addresstype WHERE id = @id", new { id }).SingleOrDefault();
        public Adjustment FindAdjustment(Guid id) => Query<Adjustment>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}adjustment WHERE id = @id", new { id }).SingleOrDefault();
        public Agreement FindAgreement(Guid id) => Query<Agreement>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}agreement WHERE id = @id", new { id }).SingleOrDefault();
        public Alert FindAlert(Guid id) => Query<Alert>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}alert WHERE id = @id", new { id }).SingleOrDefault();
        public Alias FindAlias(Guid id) => Query<Alias>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}alias WHERE id = @id", new { id }).SingleOrDefault();
        public AlternativeTitleType FindAlternativeTitleType(Guid id) => Query<AlternativeTitleType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}alternative_title_type WHERE _id = @id", new { id }).SingleOrDefault();
        public AuditLoan FindAuditLoan(Guid id) => Query<AuditLoan>($"SELECT _id AS \"Id\", orig_id AS \"OrigId\", operation AS \"Operation\", jsonb AS \"Content\", created_date AS \"CreationTime\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}audit_loan WHERE _id = @id", new { id }).SingleOrDefault();
        public AuthAttempt FindAuthAttempt(Guid id) => Query<AuthAttempt>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_attempts WHERE _id = @id", new { id }).SingleOrDefault();
        public AuthCredentialsHistory FindAuthCredentialsHistory(Guid id) => Query<AuthCredentialsHistory>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_credentials_history WHERE _id = @id", new { id }).SingleOrDefault();
        public AuthPasswordAction FindAuthPasswordAction(Guid id) => Query<AuthPasswordAction>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_password_action WHERE _id = @id", new { id }).SingleOrDefault();
        public Block FindBlock(Guid id) => Query<Block>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}manualblocks WHERE id = @id", new { id }).SingleOrDefault();
        public Budget FindBudget(Guid id) => Query<Budget>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", fund_id AS \"FundId\", fiscal_year_id AS \"FiscalYearId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}budget WHERE id = @id", new { id }).SingleOrDefault();
        public CallNumberType FindCallNumberType(Guid id) => Query<CallNumberType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}call_number_type WHERE _id = @id", new { id }).SingleOrDefault();
        public Campus FindCampus(Guid id) => Query<Campus>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", institutionid AS \"Institutionid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loccampus WHERE _id = @id", new { id }).SingleOrDefault();
        public CancellationReason FindCancellationReason(Guid id) => Query<CancellationReason>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}cancellation_reason WHERE _id = @id", new { id }).SingleOrDefault();
        public Category FindCategory(Guid id) => Query<Category>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}category WHERE id = @id", new { id }).SingleOrDefault();
        public CirculationRule FindCirculationRule(Guid id) => Query<CirculationRule>($"SELECT _id AS \"Id\", jsonb AS \"Content\", lock AS \"Lock\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}circulation_rules WHERE _id = @id", new { id }).SingleOrDefault();
        public Claim FindClaim(Guid id) => Query<Claim>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}claim WHERE id = @id", new { id }).SingleOrDefault();
        public ClassificationType FindClassificationType(Guid id) => Query<ClassificationType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}classification_type WHERE _id = @id", new { id }).SingleOrDefault();
        public Comment FindComment(Guid id) => Query<Comment>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}comments WHERE id = @id", new { id }).SingleOrDefault();
        public Contact FindContact(Guid id) => Query<Contact>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}contact WHERE id = @id", new { id }).SingleOrDefault();
        public ContactCategory FindContactCategory(Guid id) => Query<ContactCategory>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}contact_category WHERE id = @id", new { id }).SingleOrDefault();
        public ContributorNameType FindContributorNameType(Guid id) => Query<ContributorNameType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}contributor_name_type WHERE _id = @id", new { id }).SingleOrDefault();
        public ContributorType FindContributorType(Guid id) => Query<ContributorType>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}contributor_type WHERE _id = @id", new { id }).SingleOrDefault();
        public Cost FindCost(Guid id) => Query<Cost>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}cost WHERE id = @id", new { id }).SingleOrDefault();
        public Detail FindDetail(Guid id) => Query<Detail>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}details WHERE id = @id", new { id }).SingleOrDefault();
        public ElectronicAccessRelationship FindElectronicAccessRelationship(Guid id) => Query<ElectronicAccessRelationship>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}electronic_access_relationship WHERE _id = @id", new { id }).SingleOrDefault();
        public Email FindEmail(Guid id) => Query<Email>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}email WHERE id = @id", new { id }).SingleOrDefault();
        public Eresource FindEresource(Guid id) => Query<Eresource>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}eresource WHERE id = @id", new { id }).SingleOrDefault();
        public EventLog FindEventLog(Guid id) => Query<EventLog>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}event_logs WHERE _id = @id", new { id }).SingleOrDefault();
        public Fee FindFee(Guid id) => Query<Fee>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", ownerid AS \"Ownerid\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}feefines WHERE id = @id", new { id }).SingleOrDefault();
        public FeeAction FindFeeAction(Guid id) => Query<FeeAction>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}feefineactions WHERE id = @id", new { id }).SingleOrDefault();
        public FiscalYear FindFiscalYear(Guid id) => Query<FiscalYear>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fiscal_year WHERE id = @id", new { id }).SingleOrDefault();
        public FixedDueDateSchedule FindFixedDueDateSchedule(Guid id) => Query<FixedDueDateSchedule>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}fixed_due_date_schedule WHERE _id = @id", new { id }).SingleOrDefault();
        public Fund FindFund(Guid id) => Query<Fund>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", ledger_id AS \"LedgerId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fund WHERE id = @id", new { id }).SingleOrDefault();
        public FundDistribution FindFundDistribution(Guid id) => Query<FundDistribution>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", budget_id AS \"BudgetId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fund_distribution WHERE id = @id", new { id }).SingleOrDefault();
        public FundDistribution2 FindFundDistribution2(Guid id) => Query<FundDistribution2>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}fund_distribution WHERE id = @id", new { id }).SingleOrDefault();
        public Group FindGroup(Guid id) => Query<Group>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}groups WHERE id = @id", new { id }).SingleOrDefault();
        public Holding FindHolding(Guid id) => Query<Holding>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", instanceid AS \"Instanceid\", permanentlocationid AS \"Permanentlocationid\", temporarylocationid AS \"Temporarylocationid\", holdingstypeid AS \"Holdingstypeid\", callnumbertypeid AS \"Callnumbertypeid\", illpolicyid AS \"Illpolicyid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_record WHERE _id = @id", new { id }).SingleOrDefault();
        public HoldingNoteType FindHoldingNoteType(Guid id) => Query<HoldingNoteType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_note_type WHERE _id = @id", new { id }).SingleOrDefault();
        public HoldingType FindHoldingType(Guid id) => Query<HoldingType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_type WHERE _id = @id", new { id }).SingleOrDefault();
        public IdType FindIdType(Guid id) => Query<IdType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}identifier_type WHERE _id = @id", new { id }).SingleOrDefault();
        public IllPolicy FindIllPolicy(Guid id) => Query<IllPolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}ill_policy WHERE _id = @id", new { id }).SingleOrDefault();
        public Instance FindInstance(Guid id) => Query<Instance>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", instancestatusid AS \"Instancestatusid\", modeofissuanceid AS \"Modeofissuanceid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance WHERE _id = @id", new { id }).SingleOrDefault();
        public InstanceFormat FindInstanceFormat(Guid id) => Query<InstanceFormat>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_format WHERE _id = @id", new { id }).SingleOrDefault();
        public InstanceRelationship FindInstanceRelationship(Guid id) => Query<InstanceRelationship>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", superinstanceid AS \"Superinstanceid\", subinstanceid AS \"Subinstanceid\", instancerelationshiptypeid AS \"Instancerelationshiptypeid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_relationship WHERE _id = @id", new { id }).SingleOrDefault();
        public InstanceRelationshipType FindInstanceRelationshipType(Guid id) => Query<InstanceRelationshipType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_relationship_type WHERE _id = @id", new { id }).SingleOrDefault();
        public InstanceSourceMarc FindInstanceSourceMarc(Guid id) => Query<InstanceSourceMarc>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_source_marc WHERE _id = @id", new { id }).SingleOrDefault();
        public InstanceStatus FindInstanceStatus(Guid id) => Query<InstanceStatus>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_status WHERE _id = @id", new { id }).SingleOrDefault();
        public InstanceType FindInstanceType(Guid id) => Query<InstanceType>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_type WHERE _id = @id", new { id }).SingleOrDefault();
        public Institution FindInstitution(Guid id) => Query<Institution>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}locinstitution WHERE _id = @id", new { id }).SingleOrDefault();
        public Interface FindInterface(Guid id) => Query<Interface>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}interface WHERE id = @id", new { id }).SingleOrDefault();
        public Item FindItem(Guid id) => Query<Item>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", holdingsrecordid AS \"Holdingsrecordid\", permanentloantypeid AS \"Permanentloantypeid\", temporaryloantypeid AS \"Temporaryloantypeid\", materialtypeid AS \"Materialtypeid\", permanentlocationid AS \"Permanentlocationid\", temporarylocationid AS \"Temporarylocationid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}item WHERE _id = @id", new { id }).SingleOrDefault();
        public ItemNoteType FindItemNoteType(Guid id) => Query<ItemNoteType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}item_note_type WHERE _id = @id", new { id }).SingleOrDefault();
        public Ledger FindLedger(Guid id) => Query<Ledger>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}ledger WHERE id = @id", new { id }).SingleOrDefault();
        public Library FindLibrary(Guid id) => Query<Library>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", campusid AS \"Campusid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loclibrary WHERE _id = @id", new { id }).SingleOrDefault();
        public Loan FindLoan(Guid id) => Query<Loan>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}loan WHERE _id = @id", new { id }).SingleOrDefault();
        public LoanPolicy FindLoanPolicy(Guid id) => Query<LoanPolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", loanspolicy_fixedduedatescheduleid AS \"LoanspolicyFixedduedatescheduleid\", renewalspolicy_alternatefixedduedatescheduleid AS \"RenewalspolicyAlternatefixedduedatescheduleid\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}loan_policy WHERE _id = @id", new { id }).SingleOrDefault();
        public LoanType FindLoanType(Guid id) => Query<LoanType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loan_type WHERE _id = @id", new { id }).SingleOrDefault();
        public Location FindLocation(Guid id) => Query<Location>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", institutionid AS \"Institutionid\", campusid AS \"Campusid\", libraryid AS \"Libraryid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}location WHERE _id = @id", new { id }).SingleOrDefault();
        public Login FindLogin(Guid id) => Query<Login>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_credentials WHERE _id = @id", new { id }).SingleOrDefault();
        public MaterialType FindMaterialType(Guid id) => Query<MaterialType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}material_type WHERE _id = @id", new { id }).SingleOrDefault();
        public ModeOfIssuance FindModeOfIssuance(Guid id) => Query<ModeOfIssuance>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}mode_of_issuance WHERE _id = @id", new { id }).SingleOrDefault();
        public Note FindNote(Guid id) => Query<Note>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_notes{(IsMySql ? "_" : ".")}note_data WHERE id = @id", new { id }).SingleOrDefault();
        public Order FindOrder(Guid id) => Query<Order>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}purchase_order WHERE id = @id", new { id }).SingleOrDefault();
        public OrderItem FindOrderItem(Guid id) => Query<OrderItem>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}po_line WHERE id = @id", new { id }).SingleOrDefault();
        public OrderItemLocation FindOrderItemLocation(Guid id) => Query<OrderItemLocation>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}location WHERE id = @id", new { id }).SingleOrDefault();
        public Owner FindOwner(Guid id) => Query<Owner>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}owners WHERE id = @id", new { id }).SingleOrDefault();
        public PatronNoticePolicy FindPatronNoticePolicy(Guid id) => Query<PatronNoticePolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}patron_notice_policy WHERE _id = @id", new { id }).SingleOrDefault();
        public Payment FindPayment(Guid id) => Query<Payment>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}payments WHERE id = @id", new { id }).SingleOrDefault();
        public Permission FindPermission(Guid id) => Query<Permission>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_permissions{(IsMySql ? "_" : ".")}permissions WHERE _id = @id", new { id }).SingleOrDefault();
        public PermissionsUser FindPermissionsUser(Guid id) => Query<PermissionsUser>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_permissions{(IsMySql ? "_" : ".")}permissions_users WHERE _id = @id", new { id }).SingleOrDefault();
        public PhoneNumber FindPhoneNumber(Guid id) => Query<PhoneNumber>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}phone_number WHERE id = @id", new { id }).SingleOrDefault();
        public Physical FindPhysical(Guid id) => Query<Physical>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}physical WHERE id = @id", new { id }).SingleOrDefault();
        public Piece FindPiece(Guid id) => Query<Piece>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}pieces WHERE id = @id", new { id }).SingleOrDefault();
        public Proxy FindProxy(Guid id) => Query<Proxy>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}proxyfor WHERE id = @id", new { id }).SingleOrDefault();
        public Refund FindRefund(Guid id) => Query<Refund>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}refunds WHERE id = @id", new { id }).SingleOrDefault();
        public ReportingCode FindReportingCode(Guid id) => Query<ReportingCode>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}reporting_code WHERE id = @id", new { id }).SingleOrDefault();
        public Request FindRequest(Guid id) => Query<Request>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", cancellationreasonid AS \"Cancellationreasonid\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}request WHERE _id = @id", new { id }).SingleOrDefault();
        public RequestPolicy FindRequestPolicy(Guid id) => Query<RequestPolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}request_policy WHERE _id = @id", new { id }).SingleOrDefault();
        public ServicePoint FindServicePoint(Guid id) => Query<ServicePoint>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}service_point WHERE _id = @id", new { id }).SingleOrDefault();
        public ServicePointUser FindServicePointUser(Guid id) => Query<ServicePointUser>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", defaultservicepointid AS \"Defaultservicepointid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}service_point_user WHERE _id = @id", new { id }).SingleOrDefault();
        public Source FindSource(Guid id) => Query<Source>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}source WHERE id = @id", new { id }).SingleOrDefault();
        public StaffSlip FindStaffSlip(Guid id) => Query<StaffSlip>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}staff_slips WHERE _id = @id", new { id }).SingleOrDefault();
        public StatisticalCode FindStatisticalCode(Guid id) => Query<StatisticalCode>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", statisticalcodetypeid AS \"Statisticalcodetypeid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}statistical_code WHERE _id = @id", new { id }).SingleOrDefault();
        public StatisticalCodeType FindStatisticalCodeType(Guid id) => Query<StatisticalCodeType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}statistical_code_type WHERE _id = @id", new { id }).SingleOrDefault();
        public Tag FindTag(Guid id) => Query<Tag>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_tags{(IsMySql ? "_" : ".")}tags WHERE _id = @id", new { id }).SingleOrDefault();
        public Transaction FindTransaction(Guid id) => Query<Transaction>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", budget_id AS \"BudgetId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}transaction WHERE id = @id", new { id }).SingleOrDefault();
        public Transfer FindTransfer(Guid id) => Query<Transfer>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}transfers WHERE id = @id", new { id }).SingleOrDefault();
        public TransferCriteria FindTransferCriteria(Guid id) => Query<TransferCriteria>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}transfer_criteria WHERE id = @id", new { id }).SingleOrDefault();
        public Url FindUrl(Guid id) => Query<Url>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}url WHERE id = @id", new { id }).SingleOrDefault();
        public User FindUser(Guid id) => Query<User>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}users WHERE id = @id", new { id }).SingleOrDefault();
        public Vendor FindVendor(Guid id) => Query<Vendor>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor WHERE id = @id", new { id }).SingleOrDefault();
        public VendorCategory FindVendorCategory(Guid id) => Query<VendorCategory>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor_category WHERE id = @id", new { id }).SingleOrDefault();
        public VendorDetail FindVendorDetail(Guid id) => Query<VendorDetail>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}vendor_detail WHERE id = @id", new { id }).SingleOrDefault();
        public VendorType FindVendorType(Guid id) => Query<VendorType>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor_type WHERE id = @id", new { id }).SingleOrDefault();
        public Waive FindWaive(Guid id) => Query<Waive>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}waives WHERE id = @id", new { id }).SingleOrDefault();

        public IEnumerable<Account> Accounts(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Account>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}accounts{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Account2> Account2s(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Account2>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}account{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Address> Addresses(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Address>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}address{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<AddressType> AddressTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<AddressType>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}addresstype{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Adjustment> Adjustments(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Adjustment>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}adjustment{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Agreement> Agreements(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Agreement>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}agreement{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Alert> Alerts(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Alert>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}alert{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Alias> Aliases(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Alias>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}alias{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<AlternativeTitleType> AlternativeTitleTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<AlternativeTitleType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}alternative_title_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<AuditLoan> AuditLoans(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<AuditLoan>($"SELECT _id AS \"Id\", orig_id AS \"OrigId\", operation AS \"Operation\", jsonb AS \"Content\", created_date AS \"CreationTime\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}audit_loan{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<AuthAttempt> AuthAttempts(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<AuthAttempt>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_attempts{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<AuthCredentialsHistory> AuthCredentialsHistories(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<AuthCredentialsHistory>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_credentials_history{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<AuthPasswordAction> AuthPasswordActions(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<AuthPasswordAction>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_password_action{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Block> Blocks(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Block>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}manualblocks{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Budget> Budgets(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Budget>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", fund_id AS \"FundId\", fiscal_year_id AS \"FiscalYearId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}budget{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<CallNumberType> CallNumberTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<CallNumberType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}call_number_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Campus> Campuses(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Campus>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", institutionid AS \"Institutionid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loccampus{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<CancellationReason> CancellationReasons(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<CancellationReason>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}cancellation_reason{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Category> Categories(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Category>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}category{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<CirculationRule> CirculationRules(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<CirculationRule>($"SELECT _id AS \"Id\", jsonb AS \"Content\", lock AS \"Lock\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}circulation_rules{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Claim> Claims(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Claim>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}claim{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ClassificationType> ClassificationTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ClassificationType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}classification_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Comment> Comments(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Comment>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}comments{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Contact> Contacts(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Contact>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}contact{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ContactCategory> ContactCategories(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ContactCategory>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}contact_category{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ContributorNameType> ContributorNameTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ContributorNameType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}contributor_name_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ContributorType> ContributorTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ContributorType>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}contributor_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Cost> Costs(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Cost>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}cost{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Detail> Details(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Detail>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}details{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ElectronicAccessRelationship> ElectronicAccessRelationships(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ElectronicAccessRelationship>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}electronic_access_relationship{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Email> Emails(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Email>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}email{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Eresource> Eresources(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Eresource>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}eresource{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<EventLog> EventLogs(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<EventLog>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}event_logs{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Fee> Fees(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Fee>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", ownerid AS \"Ownerid\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}feefines{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<FeeAction> FeeActions(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<FeeAction>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}feefineactions{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<FiscalYear> FiscalYears(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<FiscalYear>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fiscal_year{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<FixedDueDateSchedule> FixedDueDateSchedules(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<FixedDueDateSchedule>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}fixed_due_date_schedule{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Fund> Funds(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Fund>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", ledger_id AS \"LedgerId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fund{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<FundDistribution> FundDistributions(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<FundDistribution>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", budget_id AS \"BudgetId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fund_distribution{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<FundDistribution2> FundDistribution2s(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<FundDistribution2>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}fund_distribution{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Group> Groups(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Group>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}groups{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Holding> Holdings(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Holding>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", instanceid AS \"Instanceid\", permanentlocationid AS \"Permanentlocationid\", temporarylocationid AS \"Temporarylocationid\", holdingstypeid AS \"Holdingstypeid\", callnumbertypeid AS \"Callnumbertypeid\", illpolicyid AS \"Illpolicyid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_record{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<HoldingNoteType> HoldingNoteTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<HoldingNoteType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_note_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<HoldingType> HoldingTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<HoldingType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<IdType> IdTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<IdType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}identifier_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<IllPolicy> IllPolicies(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<IllPolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}ill_policy{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Instance> Instances(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Instance>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", instancestatusid AS \"Instancestatusid\", modeofissuanceid AS \"Modeofissuanceid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<InstanceFormat> InstanceFormats(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<InstanceFormat>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_format{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<InstanceRelationship> InstanceRelationships(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<InstanceRelationship>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", superinstanceid AS \"Superinstanceid\", subinstanceid AS \"Subinstanceid\", instancerelationshiptypeid AS \"Instancerelationshiptypeid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_relationship{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<InstanceRelationshipType> InstanceRelationshipTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<InstanceRelationshipType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_relationship_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<InstanceSourceMarc> InstanceSourceMarcs(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<InstanceSourceMarc>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_source_marc{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<InstanceStatus> InstanceStatuses(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<InstanceStatus>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_status{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<InstanceType> InstanceTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<InstanceType>($"SELECT _id AS \"Id\", jsonb AS \"Content\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Institution> Institutions(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Institution>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}locinstitution{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Interface> Interfaces(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Interface>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}interface{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Item> Items(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Item>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", holdingsrecordid AS \"Holdingsrecordid\", permanentloantypeid AS \"Permanentloantypeid\", temporaryloantypeid AS \"Temporaryloantypeid\", materialtypeid AS \"Materialtypeid\", permanentlocationid AS \"Permanentlocationid\", temporarylocationid AS \"Temporarylocationid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}item{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ItemNoteType> ItemNoteTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ItemNoteType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}item_note_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Ledger> Ledgers(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Ledger>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}ledger{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Library> Libraries(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Library>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", campusid AS \"Campusid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loclibrary{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Loan> Loans(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Loan>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}loan{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<LoanPolicy> LoanPolicies(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<LoanPolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", loanspolicy_fixedduedatescheduleid AS \"LoanspolicyFixedduedatescheduleid\", renewalspolicy_alternatefixedduedatescheduleid AS \"RenewalspolicyAlternatefixedduedatescheduleid\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}loan_policy{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<LoanType> LoanTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<LoanType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loan_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Location> Locations(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Location>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", institutionid AS \"Institutionid\", campusid AS \"Campusid\", libraryid AS \"Libraryid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}location{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Login> Logins(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Login>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_credentials{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<MaterialType> MaterialTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<MaterialType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}material_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ModeOfIssuance> ModeOfIssuances(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ModeOfIssuance>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}mode_of_issuance{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Note> Notes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Note>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_notes{(IsMySql ? "_" : ".")}note_data{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Order> Orders(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Order>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}purchase_order{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<OrderItem> OrderItems(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<OrderItem>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}po_line{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<OrderItemLocation> OrderItemLocations(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<OrderItemLocation>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}location{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Owner> Owners(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Owner>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}owners{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<PatronNoticePolicy> PatronNoticePolicies(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<PatronNoticePolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}patron_notice_policy{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Payment> Payments(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Payment>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}payments{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Permission> Permissions(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Permission>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_permissions{(IsMySql ? "_" : ".")}permissions{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<PermissionsUser> PermissionsUsers(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<PermissionsUser>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_permissions{(IsMySql ? "_" : ".")}permissions_users{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<PhoneNumber> PhoneNumbers(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<PhoneNumber>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}phone_number{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Physical> Physicals(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Physical>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}physical{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Piece> Pieces(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Piece>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}pieces{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Proxy> Proxies(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Proxy>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}proxyfor{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Refund> Refunds(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Refund>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}refunds{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ReportingCode> ReportingCodes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ReportingCode>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}reporting_code{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Request> Requests(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Request>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", cancellationreasonid AS \"Cancellationreasonid\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}request{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<RequestPolicy> RequestPolicies(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<RequestPolicy>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}request_policy{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ServicePoint> ServicePoints(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ServicePoint>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}service_point{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<ServicePointUser> ServicePointUsers(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<ServicePointUser>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", defaultservicepointid AS \"Defaultservicepointid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}service_point_user{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Source> Sources(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Source>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}source{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<StaffSlip> StaffSlips(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<StaffSlip>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}staff_slips{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<StatisticalCode> StatisticalCodes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<StatisticalCode>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", statisticalcodetypeid AS \"Statisticalcodetypeid\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}statistical_code{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<StatisticalCodeType> StatisticalCodeTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<StatisticalCodeType>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}statistical_code_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Tag> Tags(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Tag>($"SELECT _id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_tags{(IsMySql ? "_" : ".")}tags{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Transaction> Transactions(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Transaction>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\", budget_id AS \"BudgetId\" FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}transaction{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Transfer> Transfers(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Transfer>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}transfers{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<TransferCriteria> TransferCriterias(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<TransferCriteria>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}transfer_criteria{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Url> Urls(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Url>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}url{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<User> Users(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<User>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_users{(IsMySql ? "_" : ".")}users{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Vendor> Vendors(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Vendor>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<VendorCategory> VendorCategories(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<VendorCategory>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor_category{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<VendorDetail> VendorDetails(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<VendorDetail>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}vendor_detail{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<VendorType> VendorTypes(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<VendorType>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor_type{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");
        public IEnumerable<Waive> Waives(string where = null, string orderBy = null, int? skip = null, int? take = null) => Query<Waive>($"SELECT id AS \"Id\", jsonb AS \"Content\", creation_date AS \"CreationTime\", created_by AS \"CreationUserId\" FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}waives{(where != null ? $" WHERE {where}" : "")}{(orderBy != null ? $" ORDER BY {orderBy}" : "")}");

        public bool AnyAccounts() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}accounts ORDER BY id", take: 1).Any();
        public bool AnyAccount2s() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}account ORDER BY id", take: 1).Any();
        public bool AnyAddresses() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}address ORDER BY id", take: 1).Any();
        public bool AnyAddressTypes() => Query($"SELECT 1 FROM diku_mod_users{(IsMySql ? "_" : ".")}addresstype ORDER BY id", take: 1).Any();
        public bool AnyAdjustments() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}adjustment ORDER BY id", take: 1).Any();
        public bool AnyAgreements() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}agreement ORDER BY id", take: 1).Any();
        public bool AnyAlerts() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}alert ORDER BY id", take: 1).Any();
        public bool AnyAliases() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}alias ORDER BY id", take: 1).Any();
        public bool AnyAlternativeTitleTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}alternative_title_type ORDER BY _id", take: 1).Any();
        public bool AnyAuditLoans() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}audit_loan ORDER BY _id", take: 1).Any();
        public bool AnyAuthAttempts() => Query($"SELECT 1 FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_attempts ORDER BY _id", take: 1).Any();
        public bool AnyAuthCredentialsHistories() => Query($"SELECT 1 FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_credentials_history ORDER BY _id", take: 1).Any();
        public bool AnyAuthPasswordActions() => Query($"SELECT 1 FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_password_action ORDER BY _id", take: 1).Any();
        public bool AnyBlocks() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}manualblocks ORDER BY id", take: 1).Any();
        public bool AnyBudgets() => Query($"SELECT 1 FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}budget ORDER BY id", take: 1).Any();
        public bool AnyCallNumberTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}call_number_type ORDER BY _id", take: 1).Any();
        public bool AnyCampuses() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loccampus ORDER BY _id", take: 1).Any();
        public bool AnyCancellationReasons() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}cancellation_reason ORDER BY _id", take: 1).Any();
        public bool AnyCategories() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}category ORDER BY id", take: 1).Any();
        public bool AnyCirculationRules() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}circulation_rules ORDER BY _id", take: 1).Any();
        public bool AnyClaims() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}claim ORDER BY id", take: 1).Any();
        public bool AnyClassificationTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}classification_type ORDER BY _id", take: 1).Any();
        public bool AnyComments() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}comments ORDER BY id", take: 1).Any();
        public bool AnyContacts() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}contact ORDER BY id", take: 1).Any();
        public bool AnyContactCategories() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}contact_category ORDER BY id", take: 1).Any();
        public bool AnyContributorNameTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}contributor_name_type ORDER BY _id", take: 1).Any();
        public bool AnyContributorTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}contributor_type ORDER BY _id", take: 1).Any();
        public bool AnyCosts() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}cost ORDER BY id", take: 1).Any();
        public bool AnyDetails() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}details ORDER BY id", take: 1).Any();
        public bool AnyElectronicAccessRelationships() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}electronic_access_relationship ORDER BY _id", take: 1).Any();
        public bool AnyEmails() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}email ORDER BY id", take: 1).Any();
        public bool AnyEresources() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}eresource ORDER BY id", take: 1).Any();
        public bool AnyEventLogs() => Query($"SELECT 1 FROM diku_mod_login{(IsMySql ? "_" : ".")}event_logs ORDER BY _id", take: 1).Any();
        public bool AnyFees() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}feefines ORDER BY id", take: 1).Any();
        public bool AnyFeeActions() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}feefineactions ORDER BY id", take: 1).Any();
        public bool AnyFiscalYears() => Query($"SELECT 1 FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fiscal_year ORDER BY id", take: 1).Any();
        public bool AnyFixedDueDateSchedules() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}fixed_due_date_schedule ORDER BY _id", take: 1).Any();
        public bool AnyFunds() => Query($"SELECT 1 FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fund ORDER BY id", take: 1).Any();
        public bool AnyFundDistributions() => Query($"SELECT 1 FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}fund_distribution ORDER BY id", take: 1).Any();
        public bool AnyFundDistribution2s() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}fund_distribution ORDER BY id", take: 1).Any();
        public bool AnyGroups() => Query($"SELECT 1 FROM diku_mod_users{(IsMySql ? "_" : ".")}groups ORDER BY id", take: 1).Any();
        public bool AnyHoldings() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_record ORDER BY _id", take: 1).Any();
        public bool AnyHoldingNoteTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_note_type ORDER BY _id", take: 1).Any();
        public bool AnyHoldingTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}holdings_type ORDER BY _id", take: 1).Any();
        public bool AnyIdTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}identifier_type ORDER BY _id", take: 1).Any();
        public bool AnyIllPolicies() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}ill_policy ORDER BY _id", take: 1).Any();
        public bool AnyInstances() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance ORDER BY _id", take: 1).Any();
        public bool AnyInstanceFormats() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_format ORDER BY _id", take: 1).Any();
        public bool AnyInstanceRelationships() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_relationship ORDER BY _id", take: 1).Any();
        public bool AnyInstanceRelationshipTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_relationship_type ORDER BY _id", take: 1).Any();
        public bool AnyInstanceSourceMarcs() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_source_marc ORDER BY _id", take: 1).Any();
        public bool AnyInstanceStatuses() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_status ORDER BY _id", take: 1).Any();
        public bool AnyInstanceTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}instance_type ORDER BY _id", take: 1).Any();
        public bool AnyInstitutions() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}locinstitution ORDER BY _id", take: 1).Any();
        public bool AnyInterfaces() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}interface ORDER BY id", take: 1).Any();
        public bool AnyItems() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}item ORDER BY _id", take: 1).Any();
        public bool AnyItemNoteTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}item_note_type ORDER BY _id", take: 1).Any();
        public bool AnyLedgers() => Query($"SELECT 1 FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}ledger ORDER BY id", take: 1).Any();
        public bool AnyLibraries() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loclibrary ORDER BY _id", take: 1).Any();
        public bool AnyLoans() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}loan ORDER BY _id", take: 1).Any();
        public bool AnyLoanPolicies() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}loan_policy ORDER BY _id", take: 1).Any();
        public bool AnyLoanTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}loan_type ORDER BY _id", take: 1).Any();
        public bool AnyLocations() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}location ORDER BY _id", take: 1).Any();
        public bool AnyLogins() => Query($"SELECT 1 FROM diku_mod_login{(IsMySql ? "_" : ".")}auth_credentials ORDER BY _id", take: 1).Any();
        public bool AnyMaterialTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}material_type ORDER BY _id", take: 1).Any();
        public bool AnyModeOfIssuances() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}mode_of_issuance ORDER BY _id", take: 1).Any();
        public bool AnyNotes() => Query($"SELECT 1 FROM diku_mod_notes{(IsMySql ? "_" : ".")}note_data ORDER BY id", take: 1).Any();
        public bool AnyOrders() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}purchase_order ORDER BY id", take: 1).Any();
        public bool AnyOrderItems() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}po_line ORDER BY id", take: 1).Any();
        public bool AnyOrderItemLocations() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}location ORDER BY id", take: 1).Any();
        public bool AnyOwners() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}owners ORDER BY id", take: 1).Any();
        public bool AnyPatronNoticePolicies() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}patron_notice_policy ORDER BY _id", take: 1).Any();
        public bool AnyPayments() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}payments ORDER BY id", take: 1).Any();
        public bool AnyPermissions() => Query($"SELECT 1 FROM diku_mod_permissions{(IsMySql ? "_" : ".")}permissions ORDER BY _id", take: 1).Any();
        public bool AnyPermissionsUsers() => Query($"SELECT 1 FROM diku_mod_permissions{(IsMySql ? "_" : ".")}permissions_users ORDER BY _id", take: 1).Any();
        public bool AnyPhoneNumbers() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}phone_number ORDER BY id", take: 1).Any();
        public bool AnyPhysicals() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}physical ORDER BY id", take: 1).Any();
        public bool AnyPieces() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}pieces ORDER BY id", take: 1).Any();
        public bool AnyProxies() => Query($"SELECT 1 FROM diku_mod_users{(IsMySql ? "_" : ".")}proxyfor ORDER BY id", take: 1).Any();
        public bool AnyRefunds() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}refunds ORDER BY id", take: 1).Any();
        public bool AnyReportingCodes() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}reporting_code ORDER BY id", take: 1).Any();
        public bool AnyRequests() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}request ORDER BY _id", take: 1).Any();
        public bool AnyRequestPolicies() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}request_policy ORDER BY _id", take: 1).Any();
        public bool AnyServicePoints() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}service_point ORDER BY _id", take: 1).Any();
        public bool AnyServicePointUsers() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}service_point_user ORDER BY _id", take: 1).Any();
        public bool AnySources() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}source ORDER BY id", take: 1).Any();
        public bool AnyStaffSlips() => Query($"SELECT 1 FROM diku_mod_circulation_storage{(IsMySql ? "_" : ".")}staff_slips ORDER BY _id", take: 1).Any();
        public bool AnyStatisticalCodes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}statistical_code ORDER BY _id", take: 1).Any();
        public bool AnyStatisticalCodeTypes() => Query($"SELECT 1 FROM diku_mod_inventory_storage{(IsMySql ? "_" : ".")}statistical_code_type ORDER BY _id", take: 1).Any();
        public bool AnyTags() => Query($"SELECT 1 FROM diku_mod_tags{(IsMySql ? "_" : ".")}tags ORDER BY _id", take: 1).Any();
        public bool AnyTransactions() => Query($"SELECT 1 FROM diku_mod_finance_storage{(IsMySql ? "_" : ".")}transaction ORDER BY id", take: 1).Any();
        public bool AnyTransfers() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}transfers ORDER BY id", take: 1).Any();
        public bool AnyTransferCriterias() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}transfer_criteria ORDER BY id", take: 1).Any();
        public bool AnyUrls() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}url ORDER BY id", take: 1).Any();
        public bool AnyUsers() => Query($"SELECT 1 FROM diku_mod_users{(IsMySql ? "_" : ".")}users ORDER BY id", take: 1).Any();
        public bool AnyVendors() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor ORDER BY id", take: 1).Any();
        public bool AnyVendorCategories() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor_category ORDER BY id", take: 1).Any();
        public bool AnyVendorDetails() => Query($"SELECT 1 FROM diku_mod_orders_storage{(IsMySql ? "_" : ".")}vendor_detail ORDER BY id", take: 1).Any();
        public bool AnyVendorTypes() => Query($"SELECT 1 FROM diku_mod_vendors{(IsMySql ? "_" : ".")}vendor_type ORDER BY id", take: 1).Any();
        public bool AnyWaives() => Query($"SELECT 1 FROM diku_mod_feesfines{(IsMySql ? "_" : ".")}waives ORDER BY id", take: 1).Any();

        public int Execute(string sql, object param = null, int? commandTimeout = null)
        {
            traceSource.TraceEvent(TraceEventType.Verbose, 0, $"{sql} {param}");
            return Connection.Execute(sql, param, Transaction, commandTimeout ?? CommandTimeout);
        }

        public object ExecuteScalar(string sql, object param = null, int? commandTimeout = null)
        {
            sql = Regex.Replace(sql, @"[\[\]]", "\"", RegexOptions.Compiled);
            traceSource.TraceEvent(TraceEventType.Verbose, 0, $"{sql} {param}");
            return Connection.ExecuteScalar(sql, param, Transaction, commandTimeout ?? CommandTimeout);
        }

        public IEnumerable<dynamic> Query(string sql, object param = null, int? skip = null, int? take = null, int? commandTimeout = null)
        {
            sql = Regex.Replace(sql, @"[\[\]]", "\"", RegexOptions.Compiled);
            if (skip != null || take != null) sql = $"{sql}{(IsMySql ? $" LIMIT {(skip == null ? $"{take}" : $"{skip}, {take ?? int.MaxValue}")}" : IsPostgreSql ? $"{(take != null ? $" LIMIT {take}" : "")}{(skip != null ? $" OFFSET {skip}" : "")}" : $" OFFSET {skip ?? 0} ROWS{(take != null ? $" FETCH NEXT {take} ROWS ONLY" : "")}")}";
            traceSource.TraceEvent(TraceEventType.Verbose, 0, $"{sql} {param}");
            return Connection.Query(sql, param, Transaction, false, commandTimeout ?? CommandTimeout);
        }

        public IEnumerable<T> Query<T>(string sql, object param = null, int? skip = null, int? take = null, int? commandTimeout = null)
        {
            sql = Regex.Replace(sql, @"[\[\]]", "\"", RegexOptions.Compiled);
            if (skip != null || take != null) sql = $"{sql}{(IsMySql ? $" LIMIT {(skip == null ? $"{take}" : $"{skip}, {take ?? int.MaxValue}")}" : IsPostgreSql ? $"{(take != null ? $" LIMIT {take}" : "")}{(skip != null ? $" OFFSET {skip}" : "")}" : $" OFFSET {skip ?? 0} ROWS{(take != null ? $" FETCH NEXT {take} ROWS ONLY" : "")}")}";
            traceSource.TraceEvent(TraceEventType.Verbose, 0, $"{sql} {param}");
            return Connection.Query<T>(sql, param, Transaction, false, commandTimeout ?? CommandTimeout);
        }

        public void Commit()
        {
            if (dbTransaction != null)
            {
                traceSource.TraceEvent(TraceEventType.Verbose, 0, "Committing transaction");
                dbTransaction.Commit();
                dbTransaction.Dispose();
                dbTransaction = dbConnection.BeginTransaction();
            }
        }

        private string SqlEncode(string value) => value.Replace("'", "''").Replace(@"\", IsMySql ? @"\\" : @"\");

        public void Dispose()
        {
            if (dbTransaction != null)
            {
                dbTransaction.Dispose();
            }
            if (dbConnection != null)
            {
                dbConnection.Dispose();
            }
        }
    }
}
